// export const league = (req, res) => res.send("4 top leagues lead football industry")
// export const pl = (req, res) => res.send("This is Premier League")
// export const laliga = (req, res) => res.send("This is La Liga")
// export const seriea = (req, res) => res.send("This is Serie A")
// export const bundesliga = (req, res) => res.send("This is Bundesliga")
